version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # ZooKeeper客户端连接端口，默认是2181
      ZOOKEEPER_TICK_TIME: 2000 # ZooKeeper的tick时间，用于心跳检测和会话超时的基准时间间隔，这里设置为2000毫秒

  broker:
    image: confluentinc/cp-kafka:7.8.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1 #  Kafka集群中Broker的唯一标识符
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      # 定义了监听器名称和它们对应的安全协议
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      # 定义了客户端用于连接到Kafka集群的监听器列表
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1