global:
  scrape_interval: 7s
  scrape_timeout: 5s
  evaluation_interval: 2s
scrape_configs:
  - job_name: aggregator
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    scheme: http
    static_configs:
      - targets: ['192.168.100.1:4000'] # The port where the aggregator is running